default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1 
  port: 15432
  password: password
  username: user

development:
  <<: *default
  database: order_distributor_development

  <<: *default
  database: order_distributor_test

production:
  <<: *default
  database: order_distributor_production
  # username: order_distributor
  # password: <%= ENV["ORDER_DISTRIBUTOR_DATABASE_PASSWORD"] %>
